name: Generate Snake

on:
  schedule: # Запускается автоматически каждый день
    - cron: "0 0 * * *"
  workflow_dispatch: # Можно запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Pugoev
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update snake animation"
          add: "dist"

